
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.md')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='smartleia_target',
    version='1.0.0',
    description='Python toolkit for LEIA smartcard reader target',
    python_requires='==3.*,>=3.7.0',
    project_urls={"documentation": "TODO", "homepage": "TODO", "repository": "TODO"},
    author='LEIA Team',
    author_email='leia@h2lab.org',
    license='LGPL-2.1+',
    packages=['smartleia_target'],
    package_dir={"": "."},
    package_data={"smartleia_target": ["*.csv", "*.ipynb"]},
    install_requires=['pyserial'],
    entry_points={
        'console_scripts': [
            'smartleia_target = smartleia_target.__main__:shell',
        ]
    },
)
